services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: data_store_dummy
      POSTGRES_USER: smartstaff
      POSTGRES_PASSWORD: 1z2x3c4v
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/MONITORING/DockerData/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "6060:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminsmartstaff@mail.com
      PGADMIN_DEFAULT_PASSWORD: 1z2x3c4v
    volumes:
      - C:/Users/MONITORING/DockerData/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "12000:12000"
    env_file:
      - .env.docker
    depends_on:
      - postgres
    volumes:
      - C:/Users/MONITORING/DockerData/uploads:/app/public/uploads

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "11000:11000"
    env_file:
      - .env.docker
    depends_on:
      - backend