// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

function resolveDatabaseUrl() {
  if (process.env["DATABASE_URL"]) {
    return process.env["DATABASE_URL"];
  }

  const user = process.env["POSTGRES_USER"] ?? "smartstaff";
  const password = process.env["POSTGRES_PASSWORD"] ?? "1z2x3c4v";
  const host = process.env["POSTGRES_HOST"] ?? "postgres";
  const port = process.env["POSTGRES_PORT"] ?? "5432";
  const database = process.env["POSTGRES_DB"] ?? "data_store_dummy";

  return `postgresql://${user}:${password}@${host}:${port}/${database}?schema=public`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? resolveDatabaseUrl(),
  },
});
